import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
export default {
  algorithmsSidebar: [
    { type: "autogenerated", dirName: "algorithms-data-structures/algorithms" },
  ],
  DataStructuresSidebar: [
    { type: "autogenerated", dirName: "algorithms-data-structures/data-structures" },
  ],
  CLangSidebar: [
    { type: "autogenerated", dirName: "programming-languages/c-lang" },
  ],
  JavaSidebar: [
    { type: "autogenerated", dirName: "programming-languages/java" },
  ],
  OSSidebar: [
    { type: "autogenerated", dirName: "operating-systems" },
   ],
  // PrinciplesTheorySidebar: [
  //   { type: "autogenerated", dirName: "software-engineering2/principles-theory" },
  // ],
} satisfies SidebarsConfig;
