import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
export default {
  //mathSidebar: [{ type: "autogenerated", dirName: "." }],
  // Sidebar for Discrete Math subtopic
  discreteMathSidebar: [
    { type: "autogenerated", dirName: "mathematics/discrete-mathematics" },
  ],
  // Sidebar for Linear Algebra subtopic
  linearAlgebraSidebar: [{ type: "autogenerated", dirName: "mathematics/linear-algebra" }],
  hardwareSidebar: [{ type: "autogenerated", dirName: "." }],
  softwareSidebar: [{ type: "autogenerated", dirName: "." }],
  embeddedSidebar: [{ type: "autogenerated", dirName: "." }],
} satisfies SidebarsConfig;
