import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
export default {
  ComputerOrganizationSidebar: [
    { type: "autogenerated", dirName: "computer-organization" },
  ],
  DigitalLogicSidebar: [
    { type: "autogenerated", dirName: "digital-logic" },
  ]
} satisfies SidebarsConfig;
