import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
export default {
  // Sidebar for Discrete Math subtopic
  discreteMathSidebar: [
    { type: "autogenerated", dirName: "discrete-mathematics" },
  ],
  // Sidebar for Linear Algebra subtopic
  linearAlgebraSidebar: [{ type: "autogenerated", dirName: "linear-algebra" }],
} satisfies SidebarsConfig;
