import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  // ================================
  // Principles Theory
  // ================================
  CorePrinciplesSidebar: [
    {
      type: 'category',
      label: 'Core Principles',
      items: [
        { type: 'autogenerated', dirName: 'principles-theory/core-principles' },
      ],
    },
  ],

  OOPPrinciplesSidebar: [
    {
      type: 'category',
      label: 'OOP Principles',
      items: [
        { type: 'autogenerated', dirName: 'principles-theory/oop-principles' },
      ],
    },
  ],

  FunctionalReactiveSidebar: [
    {
      type: 'category',
      label: 'Functional & Reactive',
      items: [
        { type: 'autogenerated', dirName: 'principles-theory/functional-reactive' },
      ],
    },
  ],

  ComplexityTradeoffsSidebar: [
    {
      type: 'category',
      label: 'Complexity Tradeoffs',
      items: [
        { type: 'autogenerated', dirName: 'principles-theory/complexity-tradeoffs' },
      ],
    },
  ],

  SystemQualitiesSidebar: [
    {
      type: 'category',
      label: 'System Qualities',
      items: [
        { type: 'autogenerated', dirName: 'principles-theory/system-qualities' },
      ],
    },
  ],

  // ================================
  // Design & Architecture
  // ================================
  SystemDesignSidebar: [
    {
      type: 'category',
      label: 'System Design',
      items: [
        { type: 'autogenerated', dirName: 'design-architecture/system-design' },
      ],
    },
  ],

  ArchitecturalStylesSidebar: [
    {
      type: 'category',
      label: 'Architectural Styles',
      items: [
        { type: 'autogenerated', dirName: 'design-architecture/architectural-styles' },
      ],
    },
  ],

  ArchitecturalPatternsSidebar: [
    {
      type: 'category',
      label: 'Architectural Patterns',
      items: [
        { type: 'autogenerated', dirName: 'design-architecture/architectural-patterns' },
      ],
    },
  ],

  DesignPatternsSidebar: [
    {
      type: 'category',
      label: 'Design Patterns',
      items: [
        { type: 'autogenerated', dirName: 'design-architecture/design-patterns' },
      ],
    },
  ],

  DistributedSystemsSidebar: [
    {
      type: 'category',
      label: 'Distributed Systems',
      items: [
        { type: 'autogenerated', dirName: 'design-architecture/distributed-systems' },
      ],
    },
  ],

  // ================================
  // Implementation
  // ================================
  CodeStructureSidebar: [
    {
      type: 'category',
      label: 'Code Structure',
      items: [
        { type: 'autogenerated', dirName: 'implementation/code-structure' },
      ],
    },
  ],

  CodingPracticesSidebar: [
    {
      type: 'category',
      label: 'Coding Practices',
      items: [
        { type: 'autogenerated', dirName: 'implementation/coding-practices' },
      ],
    },
  ],

  DependencyManagementSidebar: [
    {
      type: 'category',
      label: 'Dependency Management',
      items: [
        { type: 'autogenerated', dirName: 'implementation/dependency-management' },
      ],
    },
  ],

  DataHandlingSidebar: [
    {
      type: 'category',
      label: 'Data Handling',
      items: [
        { type: 'autogenerated', dirName: 'implementation/data-handling' },
      ],
    },
  ],

  ErrorLoggingSidebar: [
    {
      type: 'category',
      label: 'Error & Logging',
      items: [
        { type: 'autogenerated', dirName: 'implementation/error-logging' },
      ],
    },
  ],

  SecurityCodeSidebar: [
    {
      type: 'category',
      label: 'Security in Code',
      items: [
        { type: 'autogenerated', dirName: 'implementation/security-code' },
      ],
    },
  ],

  PerformanceSidebar: [
    {
      type: 'category',
      label: 'Performance',
      items: [
        { type: 'autogenerated', dirName: 'implementation/performance-optimization' },
      ],
    },
  ],

  // ================================
  // Frameworks & Platforms
  // ================================
  SpringBootSidebar: [
    {
      type: 'category',
      label: 'Spring Boot',
      items: [
        { type: 'autogenerated', dirName: 'frameworks-platforms/backend-frameworks/spring-boot' },
      ],
    },
  ],

  DjangoSidebar: [
    {
      type: 'category',
      label: 'Django',
      items: [
        { type: 'autogenerated', dirName: 'frameworks-platforms/backend-frameworks/django' },
      ],
    },
  ],

  FastAPISidebar: [
    {
      type: 'category',
      label: 'FastAPI',
      items: [
        { type: 'autogenerated', dirName: 'frameworks-platforms/backend-frameworks/fastapi' },
      ],
    },
  ],

  ExpressSidebar: [
    {
      type: 'category',
      label: 'Express.js',
      items: [
        { type: 'autogenerated', dirName: 'frameworks-platforms/backend-frameworks/express' },
      ],
    },
  ],

  FrontendFrameworksSidebar: [
    {
      type: 'category',
      label: 'Frontend Frameworks',
      items: [
        { type: 'autogenerated', dirName: 'frameworks-platforms/frontend-frameworks' },
      ],
    },
  ],

  PersistenceFrameworksSidebar: [
    {
      type: 'category',
      label: 'Persistence Frameworks',
      items: [
        { type: 'autogenerated', dirName: 'frameworks-platforms/persistence-frameworks' },
      ],
    },
  ],

  // ================================
  // Infrastructure & DevOps
  // ================================
  BuildPackagingSidebar: [
    {
      type: 'category',
      label: 'Build & Packaging',
      items: [
        { type: 'autogenerated', dirName: 'infrastructure-devops/build-packaging' },
      ],
    },
  ],

  DockerSidebar: [
    {
      type: 'category',
      label: 'Docker',
      items: [
        { type: 'autogenerated', dirName: 'infrastructure-devops/containerization/docker' },
      ],
    },
  ],

  KubernetesSidebar: [
    {
      type: 'category',
      label: 'Kubernetes',
      items: [
        { type: 'autogenerated', dirName: 'infrastructure-devops/orchestration/kubernetes' },
      ],
    },
  ],

  CICDSidebar: [
    {
      type: 'category',
      label: 'CI/CD',
      items: [
        { type: 'autogenerated', dirName: 'infrastructure-devops/cicd' },
      ],
    },
  ],

  CloudSidebar: [
    {
      type: 'category',
      label: 'Cloud',
      items: [
        { type: 'autogenerated', dirName: 'infrastructure-devops/cloud' },
      ],
    },
  ],

  MonitoringSidebar: [
    {
      type: 'category',
      label: 'Monitoring',
      items: [
        { type: 'autogenerated', dirName: 'infrastructure-devops/monitoring' },
      ],
    },
  ],

  DeploymentSidebar: [
    {
      type: 'category',
      label: 'Deployment Strategies',
      items: [
        { type: 'autogenerated', dirName: 'infrastructure-devops/deployment-strategies' },
      ],
    },
  ],

  ReliabilitySidebar: [
    {
      type: 'category',
      label: 'Reliability Engineering',
      items: [
        { type: 'autogenerated', dirName: 'infrastructure-devops/reliability' },
      ],
    },
  ],

};

export default sidebars;
