name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Install pnpm before setting up Node
      - uses: pnpm/action-setup@v3
        with:
          version: 9 # Or specify your version, e.g., 8.x

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm # 2. Change cache to pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # 3. pnpm equivalent of npm ci
        
      - name: Build website
        run: pnpm build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4